# MkDocs configuration file

# Site details
site_name: lulu recs
site_description: Recommendations for my friends!
site_author: lulu

theme:
  name: 'material'
  palette: # Palette toggle for light mode
    - scheme: default
      primary: black # Primary defines the primary color of the theme.
      accent: purple # Accent specifies the accent color of the theme.
      toggle: # toggle specifies the icon and name for toggling between light and dark modes.
        icon: material/toggle-switch
        name: Switch to dark mode
  # Palette toggle for dark mode
    - scheme: slate
      primary: white
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

## css def
extra_css:
  - stylesheets/extra.css

# Navigation configuration
nav:
  - movies: movies/index.md
  - series: series/index.md
  - music: music/index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
icon: # Maps custom MkDocs icons to different types of admonitions (alerts or messages), using icons from the Octicons set.
  admonition:
    note: octicons/tag-16
    abstract: octicons/checklist-16
    info: octicons/info-16
    tip: octicons/squirrel-16
    success: octicons/check-16
    question: octicons/question-16
    warning: octicons/alert-16
    failure: octicons/x-circle-16
    danger: octicons/zap-16
    bug: octicons/bug-16
    example: octicons/beaker-16
    quote: octicons/quote-16
features:
  - content.code.copy # Adds a copy button to code blocks.
  - navigation.sections # Enables section-based navigation.
  - navigation.path # Shows the navigation path (breadcrumbs).
  - navigation.top # Adds a "back to top" button.
  - search.suggest # Enables search suggestions.
plugins: # Lists the MkDocs plugins enabled for the site.
  - search # Adds search functionality.
copyright: >
    Copyright &copy; 2016 - 2024 Martin Donath