name: Build and push CLI doc to S3

on:
  release:
    types:
      - published
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: actions
    steps:
      - name: Check out the release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Verify release commit
        run: |
          echo "Checked out commit: $(git rev-parse HEAD)"
          echo "Expected tag: ${{ github.event.release.tag_name }}"
      - name: Pull Material for MKdocs image and build doc
        run: |
          docker pull squidfunk/mkdocs-material
          docker run --rm -i -v ${PWD}/docs:/docs squidfunk/mkdocs-material build
      - name: Download and set up AWS CLI
        run: |
          sudo apt update
          sudo apt install curl unzip -y
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
      - name: Set up AWS credentials
        env:
          DOC_ACCESS_KEY: ${{ secrets.DOC_ACCESS_KEY }}
          DOC_SECRET_KEY: ${{ secrets.DOC_SECRET_KEY }}
        run: |
          aws configure set aws_access_key_id $DOC_ACCESS_KEY
          aws configure set aws_secret_access_key $DOC_SECRET_KEY
          aws configure set region fr-par
      - name: Upload file to Scaleway Object Storage
        env:
          DOC_BUCKET_NAME: ${{ secrets.DOC_BUCKET_NAME }}
          DOC_S3_ENDPOINT: ${{ secrets.DOC_S3_ENDPOINT }}
        run: |
          aws s3 cp --recursive ./docs/site/ s3://$DOC_BUCKET_NAME --endpoint-url $DOC_S3_ENDPOINT